@startuml
start
    :登录;
    :选择查询图书按钮;
if(查看自己的借阅情况) then(no)
    :选择查询图书;
    :列出所有图书信息;
    :输入所需要查询的图书;
if(是否有该图书？) then (是)
    :显示该图书信息;
else (否)
    :提示不存在该图书;
stop
endif
    :选择查看书目信息;
if(是否有书目信息？) then (是)
    :显示该图书书目信息;
else (否)
    :提示该图书没有书目信息;
endif
stop
else (yes)
    :展示自己的数目;
stop
@enduml