@startuml
start
    :登录;
    :列出所有图书;
    :选择所需要维护的图书;
if(是否有维护图书？) then (yes)
    :显示该图书书目信息;
else (no)
    :提示不存在该图书;
stop
endif
    :维护书目;
if(修改书目信息是否成功？) then (yes)
    :确认信息;
    :更新信息;
    stop
else (no)
    :修改失败;
    stop
@enduml