@startuml
start
    :登录;
    :列出所有图书;
    :选择预定图书;
if(是否有预定图书？) then (是)
    :显示该图书信息;
else (否)
    :提示不存在此图书;
stop
endif
    :预定图书;
    :填写预定单;
if(该图书是否还有库存？) then (是)
    :图书已全部借出，不能进行预定;
stop
else (否)
    :确认预定信息;
endif
    :保存预定单;
stop
@enduml